apiVersion: v1
kind: Secret
metadata:
  name: depi-db-secret
  namespace: depi
type: Opaque
stringData:
  POSTGRES_HOST: "depidb.cngimgy48pzs.eu-north-1.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "n~Xgy[X<z5!|]ElvLLG-#T?Uzx!0"
  POSTGRES_DB: "depidb"
