apiVersion: apps/v1
kind: Deployment
metadata:
  name: depi-frontend
  namespace: depi
  labels:
    app: depi-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depi-frontend
  template:
    metadata:
      labels:
        app: depi-frontend
    spec:
      containers:
      - name: frontend
        image: nasser1tarek/depi_frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
