apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: depi-ingress
  namespace: depi
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: depi-backend
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: depi-frontend
            port:
              number: 80
